apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ai-ingress
  namespace: ai-gateway
  annotations:
    nginx.ingress.kubernetes.io/limit-rps: "10"
spec:
  ingressClassName: nginx
  rules:
  - host: ai.lab.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ai-proxy-svc
            port:
              number: 80
